config:
  fonts:
    h1: ''
    h2: ''
    h3: ''
    h4: ''
    h5: ''
    h6: ''
    title: ''
    subtitle: ''
    body: ''
  gap:
    regular: 16
    difference: 2
    variations:
      - xxxLarge
      - xxLarge
      - xLarge
      - large
      - small
      - xSmall
      - xxSmall
      - xxxSmall
  colors:
    primary:
      red:
        opacity:
          0: ''
          0.1: ''
          0.2: ''
          0.4: ''
          0.5: ''
          0.6: ''
          0.7: ''
          0.8: ''
          0.9: ''
          1: ''
        green:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        blue:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        yellow:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        orange:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        purple:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        white:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        black:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
    secondary:
      red:
        opacity:
          0: ''
          0.1: ''
          0.2: ''
          0.4: ''
          0.5: ''
          0.6: ''
          0.7: ''
          0.8: ''
          0.9: ''
          1: ''
        green:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        blue:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        yellow:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        orange:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        purple:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        white:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        black:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
    accent:
      red:
        opacity:
          0: ''
          0.1: ''
          0.2: ''
          0.4: ''
          0.5: ''
          0.6: ''
          0.7: ''
          0.8: ''
          0.9: ''
          1: ''
        green:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        blue:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        yellow:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        orange:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        purple:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        white:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''
        black:
          opacity:
            0: ''
            0.1: ''
            0.2: ''
            0.4: ''
            0.5: ''
            0.6: ''
            0.7: ''
            0.8: ''
            0.9: ''
            1: ''